services:
  site:
    build:
      dockerfile: ./Dockerfile.app
      context: .
    ports:
      - "5000:5000"
    volumes:
      - "clipdb:/app/static/ClipSelectDB"
  db:
    build:
      dockerfile: ./Dockerfile.mysql
      context: .
    ports:
      - "3306:3306"
    volumes:
      - "../mysql_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: plsnohack
  worker:
    build:
      dockerfile: ./Dockerfile.worker
      context: .
    volumes:
      - "clipdb:/ClipSelectDB"

volumes:
  clipdb:
