version: "3.2"

services:
  site:
    image: localhost:5000/clip_site
    restart: always
    depends_on:
      - "db"
    ports:
      - "5081:80"
    volumes:
      - "clipdb:/app/app/static/ClipSelectDB"
  db:
    image: localhost:5000/clip_db
    restart: always
    volumes:
      - "mysqldb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: plsnohack
  worker:
    image: localhost:5000/clip_worker
    restart: always
    depends_on:
      - "db"
    volumes:
      - "clipdb:/ClipSelectDB"
  importer:
    image: localhost:5000/clip_importer
    restart: on-failure
    depends_on:
      - "db"
    volumes:
      - "clipdb:/ClipSelectDB"

volumes:
  # change those to whatever you like
  clipdb:
    driver_opts:
      type: nfs
      o: "addr=10.217.1.10,nolock,soft,rw"
      device: ":/gv0/ClipSelectDB"
  mysqldb:
    driver_opts:
      type: nfs
      o: "addr=10.217.1.10,nolock,soft,rw"
      device: ":/gv0/mysql_clip"

