FROM archlinux:latest

RUN pacman -Syu python python-mysql-connector imagemagick --noconfirm

COPY ./bins/wait-for-it.sh /bin
COPY ./ffmpegScripts /stuff

WORKDIR /stuff
ENTRYPOINT wait-for-it.sh db:3306 -- python3 Importer.py
